# Generated by Django 3.2 on 2023-05-24 17:13

from django.db import migrations

INITIAL_TAGS = [
    {'color': '#FFA500', 'name': 'Завтрак', 'slug': 'breakfast'},
    {'color': '#008000', 'name': 'Обед', 'slug': 'lunch'},
    {'color': '#800080', 'name': 'Ужин', 'slug': 'dinner'},
]


def add_tags(apps, schema_editor):
    MainTag = apps.get_model('recipes', 'MainTag')
    for tag in INITIAL_TAGS:
        new_tag = MainTag(color=tag['color'], name=tag['name'], slug=tag['slug'])
        new_tag.save()


def remove_tags(apps, schema_editor):
    MainTag = apps.get_model('recipes', 'MainTag')
    for tag in INITIAL_TAGS:
        MainTag.objects.get(slug=tag['slug']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_tags,
            remove_tags
        ),
    ]
